### PR TITLE
Added Animation Page

### PR DESCRIPTION
**Pull request by ManishINN**
If i wrote wrong code please tell me so that i improve!

### CODE REVIEW

**Comment by amanj752** [comment]
Ok I will let you know after check.

**Comment by ManishINN** [comment]
sure !

**Review by amanj752 — COMMENTED** [review]
done

**Comment by amanj752** [comment]
you added animation but i want a landing page to show all the courses in a card and some information with some animation.

**Comment by ManishINN** [comment]
Sure!

**Pull request merged**
